const style = {
  header: {
    padding: '16vh 0 24px',
    background: 'linear-gradient(to bottom,rgba(0,0,0,0.6), #030303)',
    color: '#fff',
    height: '600px',
    overflow: 'hidden',
    boxSizing: 'border-box',
    image: {
      position: 'absolute',
      top: 0,
      zIndex: '-1',
      height: '500px',
      width: '100%',
      backgroundSize: 'cover',
      background: 'no-repeat center center fixed',
    },
    wr: {
      marginTop: '80px',
      position: 'relative',
    },
  },
  title: {
    fontWeight: '700',
    fontSize: '28px',
    lineHeight: '1.2',
    padding: '32px 0px 16px 0px',
  },
  item: {
    position: 'relative',
    width: '180px',
    height: '180px',
    background: '#fff',
    borderRadius: '5px',
    marginRight: '20px',
    cursor: 'pointer',
    boxSizing: 'border-box',
    userSelect: 'none',
    wr: {
      display: 'flex',
      width: '100%',
      height: '500px',
      overflow: 'scroll',
    },
    img: {
      width: '180px',
      height: '180px',
      borderRadius: '5px',
    },
  },
  slider: {
    circleL: {
      display: 'flex',
      aliginItems: 'center',
      justifyContent: 'center',
      position: 'absolute',
      width: '40px',
      height: '40px',
      background: '#fff',
      zIndex: '99',
      borderRadius: '50%',
      cursor: 'pointer',
      left: '-20px',
      top: '165px',
    },
    circleR: {
      display: 'flex',
      aliginItems: 'center',
      justifyContent: 'center',
      position: 'absolute',
      width: '40px',
      height: '40px',
      background: '#fff',
      zIndex: '99',
      borderRadius: '50%',
      cursor: 'pointer',
      right: '-20px',
      top: '165px',
    },
  },
};

export default style;
