const style = {
  width: '100%',
  height: '64px',
  display: 'flex',
  boxSizing: 'border-box',
  padding: '0 16px',
  alignItems: 'center',
  justifyContent: 'space-between',
  transition: 'all .2s ease',
  // background: '#030303',
  //   borderBottom: '1px solid #1D1D1D',
  position: 'fixed',
  top: '0',
  left: '0',
  zIndex: '999',
  styleBackground: {
    width: '100%',
    height: '64px',
    display: 'flex',
    boxSizing: 'border-box',
    padding: '0 16px',
    alignItems: 'center',
    justifyContent: 'space-between',
    background: '#030303',
    borderBottom: '1px solid #1D1D1D',
    position: 'fixed',
    top: '0',
    left: '0',
    zIndex: '999',
    transition: 'all .2s ease',
  },
  nav: {
    position: 'relative',
    width: '900px',
    color: 'rgba(255,255,255,0.5)',
    display: 'flex',
    justifyContent: 'center',
    fontSize: '20px',
    item: {
      color: 'rgba(255,255,255,0.5)',
      textDecoration: 'none',
      marginRight: '22px',
      cursor: 'pointer',
      active: {
        color: 'rgba(255,255,255,0.5)',
        textDecoration: 'none',
        marginRight: '22px',
        cursor: 'pointer',
        color: '#fff',
      },
    },
  },
  enter: {
    background: '#fff',
    padding: '0 16px',
    borderRadius: '2px',
    color: '#030303',
    height: '32px',
    '&:hover': {
      background: '#fff',
    },
  },
};

export default style;
